//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitPlatesWeight {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyStrings___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RevitPlatesWeight.MyStrings - Copy", typeof(MyStrings___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перед запуском плагина перейдите на 3D вид с включенным Высоким уровнем детализации.
        /// </summary>
        public static string ErrorDetailLevel {
            get {
                return ResourceManager.GetString("ErrorDetailLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается получить геометрию у элемента.
        /// </summary>
        public static string ErrorFailedToGetGeometry1 {
            get {
                return ResourceManager.GetString("ErrorFailedToGetGeometry1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможно, элемент отключен на виде.
        /// </summary>
        public static string ErrorFailedToGetGeometry2 {
            get {
                return ResourceManager.GetString("ErrorFailedToGetGeometry2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не заданы Физические свойства материала.
        /// </summary>
        public static string ErrorMaterialPhysicalParams {
            get {
                return ResourceManager.GetString("ErrorMaterialPhysicalParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет параметра.
        /// </summary>
        public static string ErrorNoParameter1 {
            get {
                return ResourceManager.GetString("ErrorNoParameter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в пластине.
        /// </summary>
        public static string ErrorNoParameter2 {
            get {
                return ResourceManager.GetString("ErrorNoParameter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Функция доступна только в Revit 2019 и выше!.
        /// </summary>
        public static string ErrorRevit2019 {
            get {
                return ResourceManager.GetString("ErrorRevit2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработано пластин.
        /// </summary>
        public static string PlatesProcessed {
            get {
                return ResourceManager.GetString("PlatesProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КМ параметризация.
        /// </summary>
        public static string TransactionName {
            get {
                return ResourceManager.GetString("TransactionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КМ.ТипЭлемента.
        /// </summary>
        public static string ValueElementTypeParamName {
            get {
                return ResourceManager.GetString("ValueElementTypeParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Орг.СпособПодсчетаМассы.
        /// </summary>
        public static string ValueElementWeightTypeParamName {
            get {
                return ResourceManager.GetString("ValueElementWeightTypeParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КМ.ГруппаКонструкций.
        /// </summary>
        public static string ValueGroupConstParamName {
            get {
                return ResourceManager.GetString("ValueGroupConstParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рзм.КорректировкаДлины.
        /// </summary>
        public static string ValueLengthCorrectedParamName {
            get {
                return ResourceManager.GetString("ValueLengthCorrectedParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О_Материал.
        /// </summary>
        public static string ValueMaterialNameParam {
            get {
                return ResourceManager.GetString("ValueMaterialNameParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рзм.Длина.
        /// </summary>
        public static string ValuePlateLengthParamName {
            get {
                return ResourceManager.GetString("ValuePlateLengthParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мрк.НаименованиеСоставноеПрефикс.
        /// </summary>
        public static string ValuePlateNameParamName {
            get {
                return ResourceManager.GetString("ValuePlateNameParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рзм.Ширина.
        /// </summary>
        public static string ValuePlateWidthParamName {
            get {
                return ResourceManager.GetString("ValuePlateWidthParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Орг.НаименованиеПрофиля.
        /// </summary>
        public static string ValueProfileNameParamName {
            get {
                return ResourceManager.GetString("ValueProfileNameParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рзм.Толщина.
        /// </summary>
        public static string ValueThicknessParamName {
            get {
                return ResourceManager.GetString("ValueThicknessParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О_Объем.
        /// </summary>
        public static string ValueVolumeParamName {
            get {
                return ResourceManager.GetString("ValueVolumeParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О_Масса.
        /// </summary>
        public static string ValueWeightParamName {
            get {
                return ResourceManager.GetString("ValueWeightParamName", resourceCulture);
            }
        }
    }
}
