//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitPlatesWeight {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RevitPlatesWeight.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open a 3D view with a Fine level of detailing before launching the plugin.
        /// </summary>
        public static string ErrorDetailLevel {
            get {
                return ResourceManager.GetString("ErrorDetailLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get an element&apos;s geometry..
        /// </summary>
        public static string ErrorFailedToGetGeometry1 {
            get {
                return ResourceManager.GetString("ErrorFailedToGetGeometry1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe the element is disabled on the view..
        /// </summary>
        public static string ErrorFailedToGetGeometry2 {
            get {
                return ResourceManager.GetString("ErrorFailedToGetGeometry2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Physical parameters are not set!.
        /// </summary>
        public static string ErrorMaterialPhysicalParams {
            get {
                return ResourceManager.GetString("ErrorMaterialPhysicalParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameter.
        /// </summary>
        public static string ErrorNoParameter1 {
            get {
                return ResourceManager.GetString("ErrorNoParameter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in a plate.
        /// </summary>
        public static string ErrorNoParameter2 {
            get {
                return ResourceManager.GetString("ErrorNoParameter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature is available only with Revit 2019 and newer!.
        /// </summary>
        public static string ErrorRevit2019 {
            get {
                return ResourceManager.GetString("ErrorRevit2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cmn_Position.
        /// </summary>
        public static string PlateNumberingParamName {
            get {
                return ResourceManager.GetString("PlateNumberingParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plates processed.
        /// </summary>
        public static string PlatesProcessed {
            get {
                return ResourceManager.GetString("PlatesProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot rolled steel plate (ASTM A36 ).
        /// </summary>
        public static string ProfileNameValue {
            get {
                return ResourceManager.GetString("ProfileNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal parametrisation.
        /// </summary>
        public static string TransactionName {
            get {
                return ResourceManager.GetString("TransactionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mtl.TypeOfElement.
        /// </summary>
        public static string ValueElementTypeParamName {
            get {
                return ResourceManager.GetString("ValueElementTypeParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mng.WeightCalculationMethod.
        /// </summary>
        public static string ValueElementWeightTypeParamName {
            get {
                return ResourceManager.GetString("ValueElementWeightTypeParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mtl.GroupOfConstructions.
        /// </summary>
        public static string ValueGroupConstParamName {
            get {
                return ResourceManager.GetString("ValueGroupConstParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dim.LengthCorrection.
        /// </summary>
        public static string ValueLengthCorrectedParamName {
            get {
                return ResourceManager.GetString("ValueLengthCorrectedParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cmn_Material.
        /// </summary>
        public static string ValueMaterialNameParam {
            get {
                return ResourceManager.GetString("ValueMaterialNameParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dim.Length.
        /// </summary>
        public static string ValuePlateLengthParamName {
            get {
                return ResourceManager.GetString("ValuePlateLengthParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mrk.CombinedMarkPrefix.
        /// </summary>
        public static string ValuePlateNameParamName {
            get {
                return ResourceManager.GetString("ValuePlateNameParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dim.Width.
        /// </summary>
        public static string ValuePlateWidthParamName {
            get {
                return ResourceManager.GetString("ValuePlateWidthParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mrk.ProfileFullName.
        /// </summary>
        public static string ValueProfileNameParamName {
            get {
                return ResourceManager.GetString("ValueProfileNameParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dim.Thickness.
        /// </summary>
        public static string ValueThicknessParamName {
            get {
                return ResourceManager.GetString("ValueThicknessParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cmn_Volume.
        /// </summary>
        public static string ValueVolumeParamName {
            get {
                return ResourceManager.GetString("ValueVolumeParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cmn_Weight.
        /// </summary>
        public static string ValueWeightParamName {
            get {
                return ResourceManager.GetString("ValueWeightParamName", resourceCulture);
            }
        }
    }
}
